# -*- coding: utf-8 -*-
"""Estequiometria.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Itb9l_iZVYGxBYcTnUXewgeo5V7fbbWt
"""

import numpy as np

'''
Código para cálculo de compostos do tipo TMx
'''

def esteq(massa_molar_T, massa_molar_M, x, q):
    # Massa molar total do composto TMx
    massa_molar_total = massa_molar_T + x * massa_molar_M

    # Número de mols do composto na amostra
    n_mols = q / massa_molar_total

    # Massas de cada elemento na proporção estequiométrica
    massa_T = n_mols * massa_molar_T
    massa_M = n_mols * x * massa_molar_M

    print(f"Massa do elemento T: {massa_T:.4f} g")
    print(f"Massa do elemento M: {massa_M:.4f} g")

    return massa_T, massa_M

# Exemplo com TiTe2
massa_molar_Ti = 47.867  # g/mol
massa_molar_Te = 127.6   # g/mol
x = 2
q = 0.2  # g

esteq(massa_molar_Ti, massa_molar_Te, x, q)